### ISSUE TITLE
Load csv file from ODSH

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#1]
## Value statement
I as a **admin**
want to **load a csv file from Open Data Sh**
so that the **user can view it as a table or map in the next step.**

## Description
Different data sources need to be connected to the application. [Open Data SH](https://schleswig-holstein.de/DE/Landesregierung/Themen/Digitalisierung/openData/openData_node.html) is one of them. Before anything can be displayed in the app the data needs to be loaded. CSV is one of the most popular formats on ODSH. The structure of the csv files differs between different datasets. Until now the following differences are known:
* With or without header of attributes keys.
* Different separators like ';' or '|' 

CORS policy of ODSH blocks all requests to csv files except from efi2.schleswig-holstein.de. Therefore some kind of proxy is needed to request the data directly from the app. Cors-anyswhere has been tested as a simpel solution in previous projects and is available [here](https://github.com/maxbischof/cors-anywhere-server). 

## Tasks
* [x] Create interface for admin to add dataset. Interface can be really simpel. The following attributes should be set by the admin: 
    * Name
    * Description
    * URL
    * Picture URL
    * Attribute Keys
    * License
    * Publisher
    * DisplayedAs
* [x] Set up proxy server
* [x] Fetch data from ODSH
* [x] Convert data to object that can be further processed in the application.
* [x] Write component tests

## Acceptance criteria
* [x] Has text based admin interface to add dataset with possibility to specify settings for csv data like:
    * Admin can define if header is available or can add keys manually.
    * Admin can define type of seperator
* [x] CSV file is available as array or object in the app to be displayed in the next step.

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
