### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#11]
## Value statement
I as a **user**
want to **view the footer section**
so that **I can checkout news on twitter and get in contact in linkedIn**

## Description
<img width="237" alt="Bildschirmfoto 2020-08-27 um 09 10 32" src="https://user-images.githubusercontent.com/30626139/91409068-2aff8e00-e845-11ea-8948-c3658b8dd340.png">

## Tasks
* [x] Add footer section
* [x] Link to twitter and linkedIn
* [x] Add tests
* [x] Add to storybook

## Acceptance criteria
* [x] Footer should be visible with icons
* [x] Links are working

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
