### ISSUE TITLE
Filter and sort tables columns

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#16]
## Value statement
I as a **Admin**
want to **sort and filter the columns of a table**
so that **only relevant columns are shown to the user and that the first column is a suitable anchor.**

## Description
This feature gives the admin the possibility to filter and sort columns. 

## Tasks
* [x] Build interface in settings.js
* [x] Add function that filters and sorts
* [x] Add component test

## Acceptance criteria
* [x] Admin has interface for filtering and sorting
* [x] Data is filtered and sorted based on admins settings for the dataset

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
