### ISSUE TITLE
Add loading icon

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#19]
## Value statement
I as a **user**
want to **see a loading spinner**
so that **I know that content is being loaded and will appear soon**

## Description
While the data for a table or graph is loaded a loading spinner should appear. 

## Tasks
* [x] Build loading spinner component
* [x] Show loading spinner while loading
* [x] Add component and integration test
* [x] Add new components to storybook

## Acceptance criteria
* [x] Loading spinner is displayed while data is loaded

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
