### ISSUE TITLE
Build root page

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#2]
## Value statement
I as a **user**
I want to **view a page when accessing root domain of the application**
so that I have an **entry point to the app.**

## Description
<img width="193" alt="Bildschirmfoto 2020-08-26 um 14 34 39" src="https://user-images.githubusercontent.com/30626139/91304137-4c12a100-e7a9-11ea-9e66-6b4682b70641.png">
The root page welcomes the user when accessing the root of the app. It contains of header, welcome section and datasets section. 

Header only consists of logo. By clicking on the logo the user is taken back to the root page.

Welcome section consists of full width header picture, headline, subheadline and cta button which links to the datasets section.

Datasets section shows all available datasets. Type of the display like table or map should be build but not be displayed until there are detail views to present data in such a way.

## Tasks
* [x] Build header with Logo: onClick -> Rootpage
* [x] Build welcome section with headline, subheadline and cta button: onClick -> Datasets section
* [x] Build datasets section
* [x] Add components tests
* [x] Add integration tests
* [x] Add new components to storybook

## Acceptance criteria
* [x] Header should be displayed and link should work
* [x] Welcome section should be displayed and link should work
* [x] Datasets section should show all available datasets

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
