### ISSUE TITLE
Search datasets by title

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#28]
## Value statement
I as a **user**
want to **want to search datasets**
so that **I can find the dataset I am looking for.**

## Tasks
* [x] Add search input field
* [x] Display search results underneath input field while typing
* [x] Write unit test

## Acceptance criteria
* [x] All datasets containing the string from the input field in title or description are displayed underneath.

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
