### ISSUE TITLE
Build dataset details view page

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#3]
## Value statement
I as a **user**
want to **view the details page of a dataset**
so that **I can see more information on the dataset and the displayed data as table, map or graph** 

## Description
<img width="238" alt="Bildschirmfoto 2020-08-28 um 09 50 15" src="https://user-images.githubusercontent.com/30626139/91535760-f3134c00-e913-11ea-8c34-37750b04f9ad.png">

## Tasks
* [x] Add Header
* [x] Build "< zurück" Button
* [x] Build dataset details with picture, title and description text

## Acceptance criteria
* [x] Header should be visible and linking to root page
* [x] Dataset details should be visible
* [x] Add component test
* [x] Add new components to storybook

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
