### ISSUE TITLE
Display appopriate error message

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#31]
## Value statement
I as a **user**
want to **see an appropriate error message related to the problem that was caused**
so that **I can retrieve information that helps me solving the problem**

## Description
At the moment different erros can occur that are mostly related to API calls. When a problem occurs the user is not getting a proper feedback about what went wrong. The issues aims to show the use a message that helps him eventually solving the problem.

## Tasks
* [x] Build hook with error state that shows message depending on error code.
* [x] Build Component that displays message to the user.
* [x] Add component and integration test

## Acceptance criteria
* [x] All API calls or User Inputs are sending a error message to the user when an error occurs.

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
