### ISSUE TITLE
Display data as table

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#4]
## Value statement
I as a **user**
want to **view the dataset as a table**
so that **I can gain insights from the dataset.**

## Description
<img width="265" alt="Bildschirmfoto 2020-08-26 um 15 14 19" src="https://user-images.githubusercontent.com/30626139/91307878-d27db180-e7ae-11ea-8a08-24b5688511a8.png">
The presentation of data as a table is the simplest way to disyplay data in the app. All columns except the first should be horizontally scrollable to give the user the possibility to explore all the data in the table.

## Tasks
* [x] Build table structure
* [x] Style table
* [x] Write component and integration tests
* [x] Add new components to storybook

## Acceptance criteria
* [x] Data should be displayed in a table
* [x] Keys should be visible in first row
* [x] First column is fixed (not scrollable)
* [x] All other columns are horizontally scrollable

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g.,  ssary).
