### ISSUE TITLE
Display data as map

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/data-hub-nord#8]
## Value statement
I as a **user**
want to **view geographical data on a map**
so that **I can see the spatial information of the data.**

## Description
Data which holds spatial information should be displayed as map. Every piece of data should have its one marker on the map. By clicking on the marker the information of the attributes should be displayed.
<img width="387" alt="Bildschirmfoto 2020-08-27 um 09 27 07" src="https://user-images.githubusercontent.com/30626139/91410642-7ca91800-e847-11ea-97bc-ad134d353007.png">

## Tasks
* [x] Add user interface for selecting adress columns or lat/long
* [x] Choose map api
* [x] Integrate map api to display base map
* [x] Add markers on map
* [x] Add attributes information to markers
* [x] Style markers & attributes information
* [x] Add tests

## Acceptance criteria
* [x] Display Map on details page
* [x] Display makers on map
* [x] Show attributes information after clicking on marker

Please note that [wiki](https://github.com/maxbischof/data-hub-nord/wiki) provides further information (e.g., glossary).
